### ISSUE TITLE
按回车不跳转到命令文档页

### ISSUE THREAD

**Issue by gd4Ark** [roojay520/alfred-linux-command#1]
在此界面按下回车并不会跳转到命令文档页

![image](https://user-images.githubusercontent.com/27952659/96239767-b1795600-0fd2-11eb-885a-af5e770b2222.png)

**Comment by roojay** [comment]
@gd4Ark  v0.2.0 已添加回车键跳转到命令文档页和 shift 键快速预览功能，重新执行 ` npm i -g alfred-linux-command` 安装一下
