### ISSUE TITLE
Can not get the information through Alfred

### ISSUE THREAD

**Issue by Mercurius-Lee** [roojay520/alfred-linux-command#2]
https://jaywcjlove.gitee.io/linux-command/c/lsblk.html<img width="284" alt="image" src="https://user-images.githubusercontent.com/31580811/128619503-f180e7b9-4e9c-49e6-ac7b-247c022e2e8b.png">

**Comment by roojay** [comment]
@Mercurius-Lee  之前的数据来源网址失效了，更新 github pages 作为数据源，更新一下试试
